volumes:
  staticfiles:

services:
  server:
    build: .
    develop:
      watch:
        - action: sync
          path: ./myapp
          target: /app/myapp
        - action: rebuild
          path: requirements.txt
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - staticfiles:/app/staticfiles

  nginx:
    build: ./deploy/nginx
    ports:
      - "8080:80"
    volumes:
      - staticfiles:/app/staticfiles
    depends_on:
      - server
