services:
  server:
    build:
      context: .
    ports:
      - 8000:8000

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"      # host:8000 -> nginx:80
    volumes:
      - static_volume:/staticfiles:ro
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server

volumes:
  static_volume: {}