volumes:
  staticfiles:
  nginx-conf:

services:
  server:
    build: .
    command: /entrypoint.sh
    volumes:
      - staticfiles:/app/staticfiles
    expose:
      - "8000"
    env_file:
      - .env  

  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/app/staticfiles
    depends_on:
      - server